### ISSUE TITLE
使用OC引导时一直卡End Randomseed

### ISSUE THREAD

**Issue by ytlmike** [y2fish/lenovo-zhaoyang-k43c-80-i7-8550u-uhd620-mac#1]
感谢你的efi，clover的可以用。
最近想升级bigsur，试了下opencore的efi。我一直卡在End Randomseed，查了查可能是cfg lock没关的原因，但我的bios没有高级选项，想问下，你的cfglock关了吗，用什么方法关的呢

**Comment by ettingshausen** [comment]
可以解锁cfg，下图是解锁之后的状态
![截屏2021-09-09 10 44 51](https://user-images.githubusercontent.com/9806325/132613863-cb2a5cde-0ada-471e-afc7-c1f7db5bbdc8.png)
这个本可以进入BIOS高级模式，方法（[来源](https://zhuanlan.zhihu.com/p/152278938)）：
>关机状态接入适配器
按一下开机键，
不断按F2
正常进入BIOS一次
按一下开机键，此时关机
依次按下“F1-1-Q-A-Z, F2-2-W-S-X, ... , F6-6-Y-H-N”一共6排30个按键
按一下开机键
不断按F2
进入高级BIOS  

@ytlmike
